// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4JtshUym5hL90fvxfe8msWfL41rVeQw',
    appId: '1:126373033532:web:04ed659048a31e02a9f539',
    messagingSenderId: '126373033532',
    projectId: 'assignmates-79fa2',
    authDomain: 'assignmates-79fa2.firebaseapp.com',
    storageBucket: 'assignmates-79fa2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsTSvZ706LZnd_ulgRAiFygSAnT9nYh8',
    appId: '1:126373033532:android:5e423a9662d4709ea9f539',
    messagingSenderId: '126373033532',
    projectId: 'assignmates-79fa2',
    storageBucket: 'assignmates-79fa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOMPJPUnThcq3q2rIudzAysJfsMVKA33A',
    appId: '1:126373033532:ios:f7ade1328be2760fa9f539',
    messagingSenderId: '126373033532',
    projectId: 'assignmates-79fa2',
    storageBucket: 'assignmates-79fa2.appspot.com',
    iosBundleId: 'com.example.assignmates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOMPJPUnThcq3q2rIudzAysJfsMVKA33A',
    appId: '1:126373033532:ios:f7ade1328be2760fa9f539',
    messagingSenderId: '126373033532',
    projectId: 'assignmates-79fa2',
    storageBucket: 'assignmates-79fa2.appspot.com',
    iosBundleId: 'com.example.assignmates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU4JtshUym5hL90fvxfe8msWfL41rVeQw',
    appId: '1:126373033532:web:6649585d80c21931a9f539',
    messagingSenderId: '126373033532',
    projectId: 'assignmates-79fa2',
    authDomain: 'assignmates-79fa2.firebaseapp.com',
    storageBucket: 'assignmates-79fa2.appspot.com',
  );
}
